version: '3.8'

include:
- ./minio/storage.compose.yml         # Ports 10000-10099 | IP: 172.20.1.X
- ./kafka/kafka.compose.yml           # Ports 10100-10199 | IP: 172.20.2.X
- ./flink/flink.compose.yml           # Ports 10200-10299 | IP: 172.20.3.X
- ./doris/doris.compose.yml           # Ports 10300-10399 | IP: 172.20.4.X
- ./monitoring/monitoring.compose.yml      # Ports 10400-10499 | IP: 172.20.5.X

networks:
  kappa:
    ipam:
      config:
        - subnet: 172.20.0.0/16