version: '3.8'

include:
- ./storage.compose.yml
# - ./kafka.compose.yml
# - ./flink.compose.yml
- ./doris.compose.yml
# - ./monitoring.compose.yml

networks:
  kappa:
    ipam:
      config:
        - subnet: 172.20.0.0/16