services:
  doris-fe:
    image: apache/doris:doris-fe-2.1.7
    hostname: doris-fe
    environment:
      - FE_SERVERS=fe1:172.20.4.2:9010
      - FE_ID=1
      - PRIORITY_NETWORKS=172.20.0.0/16
    volumes:
      - doris-fe-meta:/opt/apache-doris/fe/doris-meta/
      - doris-fe-log:/opt/apache-doris/fe/log/
    ports:
      - "10300:8030"
      - "10301:9020"
      - "10302:9030"
      - "10303:9010"
    networks:
      kappa:
        ipv4_address: 172.20.4.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.20.4.2:8030"]
      interval: 30s
      timeout: 10s
      retries: 3

  doris-be-1:
    image: apache/doris:doris-be-2.1.7
    hostname: doris-be
    environment:
      - FE_SERVERS=fe1:172.20.4.2:9010
      - BE_ADDR=172.20.4.22:9050
      - PRIORITY_NETWORKS=172.20.0.0/16
    volumes:
      - doris-be-storage-1:/opt/apache-doris/be/storage/
      - doris-be-script-1:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
    networks:
      kappa:
        ipv4_address: 172.20.4.22
  doris-be-2:
    image: apache/doris:doris-be-2.1.7
    hostname: doris-be
    environment:
      - FE_SERVERS=fe1:172.20.4.2:9010
      - BE_ADDR=172.20.4.23:9050
      - PRIORITY_NETWORKS=172.20.0.0/16
    volumes:
      - doris-be-storage-2:/opt/apache-doris/be/storage/
      - doris-be-script-2:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
    networks:
      kappa:
        ipv4_address: 172.20.4.23
  doris-be-3:
    image: apache/doris:doris-be-2.1.7
    hostname: doris-be
    environment:
      - FE_SERVERS=fe1:172.20.4.2:9010
      - BE_ADDR=172.20.4.24:9050
      - PRIORITY_NETWORKS=172.20.0.0/16
    volumes:
      - doris-be-storage-3:/opt/apache-doris/be/storage/
      - doris-be-script-3:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
    networks:
      kappa:
        ipv4_address: 172.20.4.24
volumes:
  doris-fe-meta:
  doris-fe-log:
  
  doris-be-storage-1:
  doris-be-script-1:
  doris-be-storage-2:
  doris-be-script-2:
  doris-be-storage-3:
  doris-be-script-3: