services:
  superset_redis:
    image: redis:7
    container_name: superset_redis
    restart: unless-stopped
    volumes:
      - visualization_redis:/data
    networks:
      - kappa

  superset_db:
    image: postgres:14
    container_name: superset_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset_secure_password
    volumes:
      - visualization_db:/var/lib/postgresql/data
    networks:
      - kappa

  superset:
    build:
      context: .
      dockerfile: superset.dockerfile
    container_name: superset
    restart: unless-stopped
    depends_on:
      - superset_redis
      - superset_db
    environment:
      - SUPERSET_SECRET_KEY=your_secure_secret_key_here
      - SQLALCHEMY_DATABASE_URI=postgresql://superset:superset_secure_password@superset_db:5432/superset
      - REDIS_HOST=superset_redis
      - REDIS_PORT=6379
      # Doris connection environment variables
      - DORIS_HOST=doris-fe
      - DORIS_PORT=9030
      - DORIS_USER=kappa
      - DORIS_PASSWORD=kappa
      - DORIS_DATABASE=kappa
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    ports:
      - "20500:8088"
    command: >
      bash -c "superset db upgrade &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"
    networks:
      - kappa
volumes:
  visualization_redis:
  visualization_db: