{
 "title": "Monitoring2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Throughtput and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughtput",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec{topic=\"raw.measurements\"})",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_numBytesOut{job_name=\"insert_into_default_catalog_default_database_doris_gdnews2_scores\"})",
     "legendFormat": "Flink"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kappa",
     "rawSql": "select\n    max(timestampdiff(second, ingestion_timestamp, aggregation_timestamp)) as i2s_max_diff,\n    cast(from_unixtime(floor(unix_timestamp(ingestion_timestamp) / 60) * 60) as datetime) as window_start\nfrom gdnews2_scores\ngroup by from_unixtime(floor(unix_timestamp(ingestion_timestamp) / 60) * 60)\norder by window_start"
    }
   ]
  },
  { "title": "Hardware Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "container_cpu_usage_seconds_total{image=\"flink:1.20.0\", name!=\"jobmanager\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "container_cpu_usage_seconds_total{image=\"confluentinc/cp-server:7.8.0\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "container_cpu_usage_seconds_total{image=\"confluentinc/cp-zookeeper:7.8.0\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "container_cpu_usage_seconds_total{image=\"apache/doris:fe-2.1.8\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "container_cpu_usage_seconds_total{image=\"apache/doris:be-2.1.8\"}",
     "legendFormat": "Doris Backend"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "container_memory_usage_bytes{image=\"flink:1.20.0\", name!=\"jobmanager\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "container_memory_usage_bytes{image=\"confluentinc/cp-server:7.8.0\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "container_memory_usage_bytes{image=\"confluentinc/cp-zookeeper:7.8.0\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "container_memory_usage_bytes{image=\"apache/doris:fe-2.1.8\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "container_memory_usage_bytes{image=\"apache/doris:be-2.1.8\"}",
     "legendFormat": "Doris Backend"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "container_fs_usage_bytes{image=\"flink:1.20.0\", name!=\"jobmanager\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "container_fs_usage_bytes{image=\"confluentinc/cp-server:7.8.0\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "container_fs_usage_bytes{image=\"confluentinc/cp-zookeeper:7.8.0\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "container_fs_usage_bytes{image=\"apache/doris:fe-2.1.8\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "container_fs_usage_bytes{image=\"apache/doris:be-2.1.8\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "minio_cluster_usage_total_bytes",
     "legendFormat": "Object Storage"
    }
   ]
  },
  {
   "title": "Network Transmition",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "container_network_transmit_bytes_total{name!=\"jobmanager\", image=\"flink:1.20.0\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "container_network_transmit_bytes_total{image=\"confluentinc/cp-server:7.8.0\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "container_network_transmit_bytes_total{image=\"confluentinc/cp-zookeeper:7.8.0\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "container_network_transmit_bytes_total{image=\"apache/doris:fe-2.1.8\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "container_network_transmit_bytes_total{image=\"apache/doris:be-2.1.8\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "container_network_transmit_bytes_total{image=\"minio/minio:latest\"}",
     "legendFormat": "Object Storage"
    }
   ]
  }
 ]
}