{
 "title": "Monitoring",
 "time": { "from": "2025-03-19T21:46:15.282Z", "to": "2025-03-19T21:51:28.038Z" },
 "panels": [
  { "title": "Hardware Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{image=\"flink:1.20.0\"})",
     "legendFormat": "Flink"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{image=\"confluentinc/cp-server:7.8.0\"}) + sum(container_cpu_usage_seconds_total{image=\"confluentinc/cp-zookeeper:7.8.0\"})",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{image=\"apache/doris:be-2.1.8\"}) + sum(container_cpu_usage_seconds_total{image=\"apache/doris:fe-2.1.8\"})",
     "legendFormat": "Doris"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image=\"flink:1.20.0\"})",
     "legendFormat": "Flink"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image=\"confluentinc/cp-server:7.8.0\"}) + sum(container_memory_usage_bytes{image=\"confluentinc/cp-zookeeper:7.8.0\"})",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image=\"apache/doris:be-2.1.8\"}) + sum(container_memory_usage_bytes{image=\"apache/doris:fe-2.1.8\"})",
     "legendFormat": "Doris"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image=\"confluentinc/cp-server:7.8.0\"}) + sum(container_fs_usage_bytes{image=\"confluentinc/cp-zookeeper:7.8.0\"})",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(container_fs_usage_bytes{image=\"apache/doris:be-2.1.8\"}) + sum(container_fs_usage_bytes{image=\"apache/doris:fe-2.1.8\"})",
     "legendFormat": "Doris"
    },
    {
     "expr": "minio_cluster_usage_total_bytes",
     "legendFormat": "Object Storage"
    },
    {
     "expr": "sum(container_fs_usage_bytes{image=\"flink:1.20.0\"})",
     "legendFormat": "Flink"
    }
   ]
  },
  { "title": "Throughtput and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Throughtput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\"}[1m]))",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_numRecordsInPerSecond[1m]))",
     "legendFormat": "Flink"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "kappa",
     "rawSql": "select\n    max(timestampdiff(second, ingestion_timestamp, aggregation_timestamp)) as i2s_max_diff,\n    cast(from_unixtime(floor(unix_timestamp(ingestion_timestamp) / 60) * 60) as datetime) as window_start\nfrom gdnews2_scores\ngroup by from_unixtime(floor(unix_timestamp(ingestion_timestamp) / 60) * 60)\norder by window_start"
    }
   ]
  }
 ]
}