global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: 'broker'
    static_configs:
      - targets: ['broker:8080']
    metrics_path: '/metrics'
    scheme: 'http'
  - job_name: 'topics'
    static_configs:
      - targets: ['broker:8080']
    metrics_path: '/metrics/topic'
    scheme: 'http'


    