version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - kappa
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    networks:
      - kappa
    ports:
      - 9100:9100
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - kappa
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  docker-stats-exporter:
    image: wywywywy/docker_stats_exporter:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - kappa
    restart: unless-stopped
    environment:
      - DOCKER_STATS_INTERVAL=15  # Optional: set stats collection interval in seconds

volumes:
  grafana-storage: